# -*- coding: utf-8 -*-
"""funcoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FmizYQD142_sge7CsOwZw5kP-rWLMwht

**1) Escreva um programa para ler as notas das duas avaliações de um aluno no
semestre. Faça uma função que receba as duas notas por parâmetro e calcule e
escreva a média semestral e a mensagem “PARABÉNS! Você foi aprovado!”
somente se o aluno foi aprovado (considere 6.0 a média mínima para aprovação).**
"""

def media (av1, av2):
    media = (av1 + av2) / 2

    if media >= 6:
        print("PARABÉNS! Você foi aprovado.")
    else:
        print("Reprovado")

av1 = float(input("Insira a primeira nota: "))
av2 = float(input("Insira a segunda nota: "))
media(av1, av2)

"""**2) Faça uma função que calcule a hipotenusa. Os catetos são os dados de entrada e
a hipotenusa é o dado de saída.**
"""

def teoremaPitagoras(catetoA, catetoB):
  hipotenusa = (catetoA ** 2 + catetoB ** 2) ** (1/2)
  return hipotenusa

catetoA = float(input("Valor A: "))
catetoB = float(input("Valor B: "))
hipotenusa= (catetoA, catetoB)

"""**3) Faça uma função para converter uma temperatura em graus Fahrenheit para
Celsius. A temperatura em Fahrenheit é o dado de entrada e a temperatura em
Celsius é o dado de saída. Utilize a fórmula C = (F - 32) * 5/9, onde F é a
temperatura em Fahrenheit e C é a temperatura em Celsius.**
"""

def converterGrau(fahrenheit):
  conta = (fahrenheit - 32) * 5 / 9
  return conta

celsius = converterGrau(float(input("Digite a temperatura: ")))
print(celsius)

def pesoIdeal (altura, sexo):
  
    if sexo == 1:
        fem = (62.1 * altura) - 44.7
        fem = round(fem,2)
        print("Seu peso ideal é de: {}kg".format(fem))
    elif sexo == 2:
        masc = (72.7 * altura) - 58
        masc = round(masc,2)
        print("Seu peso ideal é de: {}kg".format(masc))

sexo = int(input("Digite o sexo, sendo que 1=Feminino / 2=Masc: "))
altura = float(input("Digite sua altura: "))
pesoIdeal(altura, sexo)