# -*- coding: utf-8 -*-
"""MarianaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uj_TKfrAz0MONZEcUjoaArBsysFjRARJ

***IFC- Instituto Federal Catarinense***  
**Aluna: Mariana Yasmin Roden**

**Turma:2info3**

**Faça um algoritmo que leia dois números e mostre o produto desses números.**
"""

num1 = input("Digite um número: ")
num2 = input("Digite outro número: ") 
produto = float(num1) * float(num2)
print ("Produto = ", produto)

"""**Faça um algoritmo que leia uma temperatura em graus Fahrenheit e converta e
mostre em graus Centígrados.** 
"""

num1 = input ("D5igite uma temperatura em Fahrenheit: ")
fahrenheit = (float (num1) - 32) * 5/9
print ("Centígrados= " , fahrenheit)

"""**Faça um algoritmo que calcule o volume de uma lata de óleo**

"""

import math
raio = float(input ("Digite o raio da sua lata de óleo: "))
altura = float(input ("Digite a altura da sua lata de óleo "))
volume = math.pi * raio**2 * altura
print ("O volume da sua lata de óleo é = ", volume)

"""**Faça um algoritmo que leia o tempo de duração de um evento em uma fábrica  expressa em segundos e mostre-o expresso em horas, minutos e segundos**"""

tempo = float (input ("Digite o tempo de duração do evento em segundos: "))
minutos = (tempo) / 60
horas = (minutos) / 60
print ("O tempo de duração do evento em horas é = ", horas)
print ("O tempo de duração do evento em minutos é = ", minutos)
print ("O tempo de duração do evento em segundos é = ", tempo)

"""**Faça um algoritmo que leia a idade de uma pessoa expressa em dias e mostre-a  expressa em anos, meses e dias.**

"""

idade = float (input (" Digite sua idade: "))
meses = (idade) * 12
dias = (idade) * 365
print (" Sua idade em anos é = ", idade)
print (" Sua idade em meses é = ", meses)
print (" Sua idade em dias é = ", dias)

"""**Faça um algoritmo que leia uma certa quantidade de chuva em polegadas e escreva  o equivalente em milímetros.**"""

num1 = input ("Digite a quantidade de chuva em polegadas: ")
chuva = float (num1) * 25.4
print ("Quantidade de chuva em milímetros:  ", chuva)